name: Cron workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: false
  schedule:
    - cron: "*/10 * * * *"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: |
          echo "Hello World"
